version: 2
jobs:
    deploy-website:
        docker:
            - {image: 'circleci/node:7.10'}
        steps:
            - checkout
            - {run: {name: 'Deploying to GitHub Pages', command: "git config --global user.email \"6uhrmittag@users.noreply.github.com\"\ngit config --global user.name \"6uhrmittag\"\necho \"machine github.com login 6uhrmittag password $GITHUB_TOKEN\" > ~/.netrc\ncd website && yarn install && GIT_USER=6uhrmittag yarn run publish-gh-pages\n"}}
workflows:
    version: 2
    build_and_deploy:
        jobs:
            - {deploy-website: null}
